spring:
    datasource:
        username: root
        password: 1234Aa123
        url: jdbc:mysql://localhost:3306/keycloak_database
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/keycloakSSO
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
                    auth:
                        converter:
                            resource-id: keycloak_rest_api
                            principle-attribute: preferred_username

server:
    port : 8081


jwt:
    auth:
        converter:
            resource-id: keycloak_rest_api
            principle-attribute: preferred_username